### ISSUE TITLE
Update Docs and Re-publish

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-github#32]
The `code` in this package/repo works. ✅ 🎉 
But there is nowhere _near_ enough documentation for someone _`else`_ to use the package without reading the code in `/lib` ... as a result only we (@dwyl) are using it and nobody `else` is benefiting from it.

We need to _comprehensively_ document the package (a) because it makes it easier to maintain, (b) it makes it easier (_possible_) for other people to use it and get their GitHub Auth enabled projects off the ground and (c) other people in the elixir/dwyl community can _contribute_ improvements.
Similar to https://github.com/dwyl/elixir-auth-google/issues/10 and PR: https://github.com/dwyl/elixir-auth-google/pull/11

Thankfully _this_ package's [/lib/elixir_auth_github.ex](https://github.com/dwyl/elixir-auth-github/blob/44021233add025348f261f5bf0b9b32fe6c5711a/lib/elixir_auth_github.ex) already has pretty decent `@doc` comments 👍 
So all that is _missing_ is are the detailed instructions for getting it setup.

Compare the difference:
**`before`**: https://github.com/dwyl/elixir-auth-google/tree/2b1f9b09433fb7845dff00f593edd8fa29825f5f
**`after`**: https://github.com/dwyl/elixir-auth-google/tree/71c022afee27e2cc377936c686538afa8e08d13e

# Todo

+ [x] add GitHub credentials instructions similar to https://github.com/dwyl/hapi-auth-github/blob/master/GITHUB-APP-STEP-BY-STEP-GUIDE.md
  > https://github.com/settings/applications/1190344
+ [x] Create "Sign in with GitHub" button in CSS & SVG #33 
+ [x] Create a `demo` app similar to https://github.com/dwyl/elixir-auth-google-demo
  + [x] Deploy the demo app to Heroku so people can test it. 
   > https://dashboard.heroku.com/apps/elixir-auth-github-demo/settings
+ [x] extend the `README.md` with _comprehensive_ instructions for adding `elixir-auth-github` to a sample Phoenix App. 
+ [x] Re-publish the `hex.pm` package
+ [x] update any @dwyl apps that _consume_ this package.

**`before`**:  https://github.com/dwyl/elixir-auth-github/tree/44021233add025348f261f5bf0b9b32fe6c5711a
**`after`**: 🔜 https://github.com/dwyl/elixir-auth-github/tree/update-docs-issue%2332

**Comment by nelsonic** [comment]
Continue: https://github.com/dwyl/elixir-auth-github-demo#-continue-here

**Comment by nelsonic** [comment]
Demo App working ...

http://localhost:4000/
![image](https://user-images.githubusercontent.com/194400/73599088-91366380-4537-11ea-84aa-b473da4ca379.png)

![image](https://user-images.githubusercontent.com/194400/73599092-a4493380-4537-11ea-871a-9f9e0ba29a40.png)
If you are a member of a few orgs, keep scrolling until you see the **`Authorize nelsonic`** button:
![image](https://user-images.githubusercontent.com/194400/73599098-b32fe600-4537-11ea-8ccd-d468d3607038.png)

Once you authorize the app, you will be redirected back to the Phoenix App and will see:
![image](https://user-images.githubusercontent.com/194400/73599112-e8d4cf00-4537-11ea-8379-a58affbea560.png)

# 🚀

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/73600128-16c01080-4544-11ea-8d34-b45bba1c3576.png)
Auth Step:
![image](https://user-images.githubusercontent.com/194400/73600133-23dcff80-4544-11ea-9a99-f357c7c3d497.png)
Success:
![image](https://user-images.githubusercontent.com/194400/73600142-3b1bed00-4544-11ea-977a-a38bbe5f129c.png)

That was a _good_ day! :shipit:
