### ISSUE TITLE
Sign in with GitHub Button

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-github#33]
At present we do not have any recommendation for the look-and-feel of the **Sign in with GitHub** button which means it's left to the developer to implement their own ...

The @dwyl library app is using this Elixir package: https://dwyl-library.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/71004800-5b9a0000-20da-11ea-9b59-557a812465e7.png)

When any of the (_three teal_) **Login** buttons on the page is clicked the user is redirected to GitHub auth:
![library](https://user-images.githubusercontent.com/194400/60160598-9a1ac600-97ed-11e9-9157-e4ec6a993b81.png)

There is no indication on the home page of the library app that **Login** is going to **GitHub** ... 

Yes, if one _hovers_ over one of the buttons in a _Desktop_ browser, the URL will be visible:
![github-link-on-hover](https://user-images.githubusercontent.com/194400/71030194-e265d180-2108-11ea-89dc-d184d9e10533.png)
But that is not very _mobile-first_ ... 🙄 

This is the button we have used in the past: https://github.com/dwyl/hapi-auth-github
![github-auth-logo](https://cloud.githubusercontent.com/assets/194400/11214293/4e309bf2-8d38-11e5-8d46-b347b2bd242e.png)
But it's quite different from the Google button ... https://github.com/dwyl/app/issues/249
If we want all our "Sign in with ..." buttons to have a _consistent_ look-and-feel, 
we need to make some effort to _(re)create_ the button from _first principals_. 

# Todo

+ [x] Create a button using CSS and SVG that is responsive 
  + [x] conforms to the _Google_ (_yes, Google_) button [spec](https://developers.google.com/identity/branding-guidelines#padding) so we have [_consistency_](https://github.com/dwyl/elixir-auth-google/issues/25):
![image](https://user-images.githubusercontent.com/194400/71029683-cdd50980-2107-11ea-8727-089f3b0ecf76.png)
    + [x] uses Roboto font (_to be consistent with Google button_) 
+ [x] Background Color `#24292e` (_the [super-dark grey](https://www.colorhexa.com/24292e) of GitHub navbar_)  
+ [x] Font color   `#fff` (_white_) 

The GitHub Logo _optimised_ SVG is:

```html
<svg height="32" viewBox="0 0 16 16" width="32">
  <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>
</svg>
```

> The work done for _this_ issue will be re-useable for https://github.com/dwyl/elixir-auth-google/issues/25 ♻️

**Comment by nelsonic** [comment]
The Google Spec (_above_) for the "_Sign in with Google_" button specifies dimensions/widths in **`dp`**.

What's **`dp`** (***density independent pixels***) units with CSS? 
https://stackoverflow.com/questions/16390762/whats-dp-density-independent-pixels-units-with-css

> "_When writing CSS, use px wherever dp or sp is stated. Dp only needs to be used in developing for Android._"

Futher background reading: 
+ Understanding layout: https://material.io/design/layout/understanding-layout.html#usage
+ "Why UI designers are using “dp” instead of “pixel” as unit to design mobile apps?" 
https://medium.com/mockingbot/why-ui-designers-are-using-dp-instead-of-pixel-as-unit-to-design-mobile-app-2c080f90936b

<hr />

Yes, I know there is a certain irony in me wasting time on pixel-perfect buttons in light of us switching to [`elm-ui`](https://github.com/dwyl/learn-elm/tree/master/tutorials/elm-ui) but we need auth to be 100% server-side rendered for the foreseeable future (_until we build a "native" app_) and we don't want to _impose_ the use of Tachyons on people consuming _this_ Elixir package.

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/71207708-6651c200-229f-11ea-9a82-3fc977dddf7f.png)

It's basically **`done`**, right? 😉

**Comment by nelsonic** [comment]
Apparently, **`display:flex`** has _good_ browser support: https://caniuse.com/#feat=flexbox

![image](https://user-images.githubusercontent.com/194400/71246276-3b528700-230e-11ea-9ed7-08695ebe8043.png)

So ... read this: https://css-tricks.com/snippets/css/a-guide-to-flexbox

**Comment by nelsonic** [comment]
This is what I wanted:
![image](https://user-images.githubusercontent.com/194400/71247179-20811200-2310-11ea-9f56-8bb728fd954c.png)


Code that works in all "modern" browsers (and is backwards compatible to IE 10!):
```html
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap">
<a href="#"
  style="display:inline-flex; align-items:center; min-height:40px;
    background-color:#24292e; font-family:'Roboto',sans-serif;
    font-size:14px; color:white; text-decoration:none;
    padding:8px 12px 8px 0px;">
  <svg height="18" viewBox="0 0 16 16" width="40px" style="fill:white;">
    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38
    0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01
    1.08.58 1.23.82.72 1.21 1.87.87
    2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12
    0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08
    2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0
    .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>
  </svg>
  Sign in with GitHub
</a>
```

Using http://bytesizematters.com we see that our SVG+CSS button is only **`1kb`**:
![byte-size-of-github-button](https://user-images.githubusercontent.com/194400/71247098-fcbdcc00-230f-11ea-883d-8ed4d428846b.png)

That is an **87.5%** bandwidth saving on the **`8kb`** of the [**`.png`** button](https://github.com/dwyl/elixir-auth-google/issues/25). 
And what's _more_ it reduces the number of HTTP requests which means the page loads _even_ faster. 

This is what I ***`expect`*** _everyone_ @dwyl to be doing. 
Save _everyone_ bandwidth (_and time_) by putting a little extra effort to _optimise_ the _little_ things.

**Comment by nelsonic** [comment]
Now I'm working on https://github.com/dwyl/elixir-auth-google/issues/25 with the stated objective of keeping the buttons _consistent_. So while trying to match the GitHub Button to the Google one ... this happened:
![image](https://user-images.githubusercontent.com/194400/71250752-5de99d80-2318-11ea-90f8-ab923204ee33.png)

Gotta _love_ doing layout _manually_ ... 🤦‍♂ 

Obvs this is [PEBKAC](https://en.wikipedia.org/wiki/User_error) ... and I fixed it immediately.
And after much pixel shifting, arrived at the desired result: (`class="debug"`)
![image](https://user-images.githubusercontent.com/194400/71252294-81164c00-231c-11ea-95b6-2a6e7140d8a5.png)

_Consistent_ buttons compliant with Google Spec:
![image](https://user-images.githubusercontent.com/194400/71252392-cb97c880-231c-11ea-87f7-9c198ed5f046.png)

**Comment by nelsonic** [comment]
Final code for consistently _pixel-perfect_ scalable sign in buttons:
```html
<div style="display:flex; flex-direction:column; width:180px; margin-left:20px">
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap">
  <a href="#"
    style="display:inline-flex; align-items:center; min-height:30px;
      background-color:#24292e; font-family:'Roboto',sans-serif;
      font-size:14px; color:white; text-decoration:none;">
    <div style="margin: 1px; padding-top:5px; min-height:30px;">
    <svg height="18" viewBox="0 0 16 16" width="32px" style="fill:white;">
      <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38
      0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01
      1.08.58 1.23.82.72 1.21 1.87.87
      2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12
      0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08
      2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0
      .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>
    </svg>
    </div>
    <div style="margin-left: 5px;">
      Sign in with GitHub
    </div>
  </a>

  <a href="#"
    style="display:inline-flex; align-items:center; min-height:30px;
      background-color:#4285F4; font-family:'Roboto',sans-serif;
      font-size:14px; color:white; text-decoration:none;
      margin-top: 12px">
      <div style="background-color: white; margin:1px; padding-top:5px;
       min-height:29px;">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 533.5 544.3"
        width="30px" height="18" style="display:inline-flex; align-items:center;" >
        <path d="M533.5 278.4c0-18.5-1.5-37.1-4.7-55.3H272.1v104.8h147c-6.1 33.8-25.7 63.7-54.4 82.7v68h87.7c51.5-47.4 81.1-117.4 81.1-200.2z" fill="#4285f4"/>
        <path d="M272.1 544.3c73.4 0 135.3-24.1 180.4-65.7l-87.7-68c-24.4 16.6-55.9 26-92.6 26-71 0-131.2-47.9-152.8-112.3H28.9v70.1c46.2 91.9 140.3 149.9 243.2 149.9z" fill="#34a853"/>
        <path d="M119.3 324.3c-11.4-33.8-11.4-70.4 0-104.2V150H28.9c-38.6 76.9-38.6 167.5 0 244.4l90.4-70.1z" fill="#fbbc04"/>
        <path d="M272.1 107.7c38.8-.6 76.3 14 104.4 40.8l77.7-77.7C405 24.6 339.7-.8 272.1 0 169.2 0 75.1 58 28.9 150l90.4 70.1c21.5-64.5 81.8-112.4 152.8-112.4z" fill="#ea4335"/>
      </svg>
    </div>
    <div style="margin-left: 7px;">
      Sign in with Google
    </div>
  </a>
<div>
```

![image](https://user-images.githubusercontent.com/194400/71252605-609ac180-231d-11ea-8b3e-f72d80fb2485.png)

![image](https://user-images.githubusercontent.com/194400/71252636-7a3c0900-231d-11ea-9cfc-2faa02d49507.png)

![image](https://user-images.githubusercontent.com/194400/71252665-8758f800-231d-11ea-850e-70fe6ed3eb16.png)

![image](https://user-images.githubusercontent.com/194400/71252943-4a413580-231e-11ea-8fa9-75a773114075.png)


I'm no CSS/Flexbox layout so I _encourage_ you to dissect and _improve_ this!

**Comment by nelsonic** [comment]
![img-vs-svg-button](https://user-images.githubusercontent.com/194400/73606464-71885500-45a2-11ea-995c-9abdd4c6b983.png)

**Comment by nelsonic** [comment]
Implemented in #34 :shipit:
