### ISSUE TITLE
Update HTTPoison + Publish New Version

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-github#52]
While updating to **Phoenix `1.6`** and **Elixir `1.12.3`** as part of https://github.com/dwyl/elixir-auth-github-demo/issues/17 we spotted an issue with `HTTPoison.Base`:

![image](https://user-images.githubusercontent.com/194400/134896159-280761b7-1498-485e-b417-2d71d1f2efc3.png)

My hypothesis is that simply updating to the latest version of the package will resolve this issue.

# Todo

+ [ ] Update `httpoison` to `1.8.0` https://hex.pm/packages/httpoison
+ [ ] Update `poison` to `5.0.0` https://hex.pm/packages/poison
+ [ ] Run tests
+ [ ] Create Pull Request
+ [ ] Publish new version of package `1.4.1` > `1.5.0`

Happy for _anyone_ `else` to do this update. 
Should only take 5 mins to update the `mix.exs` file and create the PR. 💭

**Comment by nelsonic** [comment]
Annoyingly when `HTTPoison` is update, one of the tests fails:
```
Generated excoveralls app
==> httpoison
Compiling 3 files (.ex)
Generated httpoison app
==> elixir_auth_github
Compiling 2 files (.ex)
Generated elixir_auth_github app


  1) test login_url/0 returns authorize URL with client_id appended (ElixirAuthGithubTest)
     test/elixir_auth_github_test.exs:13
     ** (ArgumentError) errors were found at the given arguments:

       * 1st argument: not a bitstring

     code: "https://github.com/login/oauth/authorize?client_id=" <> client_id()
     stacktrace:
       :erlang.byte_size(nil)
       test/elixir_auth_github_test.exs:15: (test)

........

Finished in 0.06 seconds (0.00s async, 0.06s sync)
9 tests, 1 failure

Randomized with seed 416996
```

**Comment by nelsonic** [comment]
PEBKAC ...
I had to `source .env` before running the tests.
Then they all pass.

**Comment by nelsonic** [comment]
PR: #53 
Package published to https://hex.pm/packages/elixir_auth_github/1.5.0
