### ISSUE TITLE
Replace Poison with Jason

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-github#54]
As noted by @abradburne in https://github.com/dwyl/elixir-auth-google/pull/48 `Jason` is the default `JSON` library in `Phoenix`
So replacing it in this project will mean one fewer dependency in the projects that "consume" (use) the package.

# Todo

+ [x] Replace `poison` with `jason`
+ [x] Update the version in `mix.exs` to `1.6.0`
+ [x] Create PR
+ [x] Publish new version to Hex.pm
